services:
  app:
    build: src
    command: [ "python", "manage.py", "runserver", "0.0.0.0:80" ]
    ports:
      - "80:80"
    env_file:
      - src/local.env
    volumes:
      - "./src:/app"
    depends_on:
      - db
  db:
    image: postgres:17.4-bookworm
    environment:
      POSTGRES_DB: "lith_pg_db"
      POSTGRES_USER: "lith_pg_user"
      POSTGRES_PASSWORD: "lith_pg_password"
    volumes:
      - "./docker/data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
